apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  namespace: angular
  labels:
    app: angular
spec:
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: argocdtest.azurecr.io/github-evry-bergen/toolbox-reference-angular:develop-2fbc38b1-11
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 4200