apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: system
spec:
  releaseName: cert-manager
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: "v1.7.1"
      sourceRef:
        kind: HelmRepository
        name: cert-manager-jetstack
        namespace: flux-system
  values:
    installCRDs: true