#------------------------------
# INFO
#------------------------------
# Kustomization to order the isntalation of argocd applications

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  path: "apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  # depends on other kustomization object
    - name: rest