#------------------------------
# INFO
#------------------------------
# Kustomization to be able to insatll cert-manager resources 
# after cert-manager itself is installe using dependsOn

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-resources
  namespace: flux-system
spec:
  interval: 5m
  path: "src/system/cert-manager/resources"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  # depends on other kustomization object
    - name: flux-system