apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: system
spec:
  releaseName: nginx-ingress
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress
      version: "9.9.5"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system