apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: angular
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: angular
  filterTags:
    pattern: '^develop-[a-zA-Z0-9]+-(?P<ghrun>.*)'
    extract: '$ghrun'
  policy:
    numerical:
      order: asc