apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  releaseName: argocd
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: "4.2.2"
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: flux-system