apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager
  namespace: system
spec:
  dnsNames:
    - alertmanager.magnifikboutique.online
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: alertmanager-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: system
spec:
  dnsNames:
    - grafana.magnifikboutique.online
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: grafana-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus
  namespace: system
spec:
  dnsNames:
    - prometheus.magnifikboutique.online
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: prometheus-tls

