apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: apps
  namespace: flux-system
spec:
    interval: 1m0s
    url: https://github.com/theartusz/demo-cluster-gitops-apps.git
    ref:
      branch: main
    secretRef:
      name: git-cred