apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: angular
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: angular
    namespace: flux-system
  filterTags:
    pattern: '^develop-[a-zA-Z0-9]+-(?P<gh_run>.*)'
    extract: '$gh_run'
  policy:
    numerical:
      order: asc