apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: angular
  namespace: flux-system
spec:
  interval: 5m
  image: magnifikacr.azurecr.io/reference-angular
  secretRef:
    name: acr-auth
