apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-community
  namespace: system
spec:
  releaseName: prometheus-community
  interval: 5m
  timeout: 20m0s
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "33.2.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    alertmanager:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
#          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - alertmanager.magnifikbutik.eu
        paths:
          - /
        pathType: Prefix
        tls:
          - hosts:
            - alertmanager.magnifikbutik.eu
            secretName: alertmanager-tls
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
#          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - grafana.magnifikbutik.eu
        paths:
          - /
        pathType: Prefix
        tls:
          - hosts:
            - grafana.magnifikbutik.eu
            secretName: grafana-tls
    prometheus:
#      ingress:
#        enabled: true
#        annotations:
#          kubernetes.io/ingress.class: "nginx"
#          nginx.ingress.kubernetes.io/ssl-redirect: "false"
#          cert-manager.io/cluster-issuer: "letsencrypt-prod"
#        hosts:
#        - prometheus.magnifikboutique.online
#        paths:
#          - /
#        pathType: Prefix
#        tls:
#          - hosts:
#            - prometheus.magnifikboutique.online
#            secretName: prometheus-tls
      prometheusSpec:
        externalUrl: http://prometheus.magnifikbutik.eu
        resources:
          limits:
            memory: 500Mi
            cpu: 200m
          requests:
            memory: 200Mi
            cpu: 30m